import type { Meta, StoryObj } from '@storybook/react-vite'
import { expect } from 'storybook/test'
import { QRCode } from './QRCode'
import { sampleQrMatrixSvg } from './sampleQrMatrix'

/**
 * A real code, generated by Dub for this URL. Deck encodes nothing, so the
 * matrix is supplied — here as inline SVG, in production as whatever your
 * generator returns.
 */
const Matrix = () => (
  <span
    style={{ display: 'block', width: '100%', height: '100%' }}
    dangerouslySetInnerHTML={{ __html: sampleQrMatrixSvg }}
  />
)

const VALUE = 'meetcard.io/ben@meetcard'

const meta = {
  component: QRCode,
  title: 'Build/Atoms/QRCode',
  tags: ['atom'],
  args: { value: VALUE, children: <Matrix /> },
} satisfies Meta<typeof QRCode>

export default meta
type Story = StoryObj<typeof meta>

/** The mark sits in the centre the generator reserved for it. */
export const Default: Story = {
  play: async ({ canvas }) => {
    // The URL is not drawn; it reaches assistive tech through the label.
    await expect(
      canvas.getByRole('img', { name: `QR code for ${VALUE}` }),
    ).toBeVisible()
    await expect(canvas.queryByText(VALUE)).toBeNull()
  },
}

export const Sizes: Story = {
  render: (args) => (
    <div style={{ display: 'flex', alignItems: 'center', gap: 16, flexWrap: 'wrap' }}>
      {(['sm', 'md', 'lg'] as const).map((size) => (
        <QRCode key={size} {...args} size={size}>
          <Matrix />
        </QRCode>
      ))}
    </div>
  ),
}

/**
 * A bare matrix. Use this when the code was generated without a reserved
 * centre — a mark laid over live modules is a code that will not scan.
 */
export const WithoutMark: Story = {
  args: { logo: null },
  play: async ({ canvasElement }) => {
    await expect(canvasElement.querySelector('.deck-qrcode__logo')).toBeNull()
  },
}

/** The share view — as large as the viewport allows, held up to be scanned. */
export const ShareView: Story = {
  args: { size: 'xl' },
}
