import { forwardRef } from 'react'
import type { HTMLAttributes, ReactNode } from 'react'
import { cx } from '../../lib/cx'
import './QRCode.css'

export type QRCodeSize = 'sm' | 'md' | 'lg' | 'xl'

export interface QRCodeProps
  extends Omit<HTMLAttributes<HTMLDivElement>, 'children'> {
  /**
   * The URL the code encodes, e.g. `https://metcard.io/ben`. Displayed
   * beneath the code and used as the accessible description, so the value is
   * readable by someone who cannot scan.
   */
  value: string
  /** Rendered QR image, e.g. the Dub.co-generated PNG or SVG data URI. */
  src?: string
  /** Inline `<svg>` alternative to `src`, for a locally rendered code. */
  children?: ReactNode
  size?: QRCodeSize
  /** Show the encoded URL under the code. Defaults to true. */
  showValue?: boolean
  /** Center overlay, typically the MeetCard mark. Keep it under ~20% width. */
  logo?: ReactNode
  /** Caption above the code, e.g. "Scan to save my card". */
  caption?: ReactNode
}

/**
 * The scannable code that carries a MeetCard.
 *
 * Presentation only — Deck does not encode QR data. Per the platform
 * architecture, codes are generated by Dub.co against the short domain so
 * they stay trackable and on-brand; pass the result as `src`, or supply your
 * own inline `<svg>` as children.
 *
 * The code always renders on an explicit light plate with a quiet zone,
 * regardless of theme: scanners need a light background and high contrast,
 * so this must NOT invert in dark mode. That is a deliberate exception to
 * Deck's theming, not an oversight.
 *
 * @example
 * <QRCode value="https://metcard.io/ben" src={qrUrl} caption="Scan to connect" />
 */
export const QRCode = forwardRef<HTMLDivElement, QRCodeProps>(function QRCode(
  {
    value,
    src,
    children,
    size = 'md',
    showValue = true,
    logo,
    caption,
    className,
    ...props
  },
  ref,
) {
  return (
    <div
      ref={ref}
      className={cx('deck-qrcode', `deck-qrcode--${size}`, className)}
      {...props}
    >
      {caption ? <p className="deck-qrcode__caption">{caption}</p> : null}

      <div className="deck-qrcode__plate">
        <div className="deck-qrcode__code">
          {src ? (
            <img
              className="deck-qrcode__image"
              src={src}
              alt={`QR code for ${value}`}
            />
          ) : (
            /* Inline codes are decorative markup; the value below carries
               the meaning for assistive tech. */
            <div className="deck-qrcode__inline" role="img" aria-label={`QR code for ${value}`}>
              {children}
            </div>
          )}

          {logo ? (
            <span className="deck-qrcode__logo" aria-hidden="true">
              {logo}
            </span>
          ) : null}
        </div>
      </div>

      {showValue ? <p className="deck-qrcode__value">{value}</p> : null}
    </div>
  )
})
